version: '3'
services:

  influxdb:
    container_name: influxdb
    image: influxdb:1.7-alpine
    ports:
      - 8086:8086

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.5.4
    ports:
      - 9200:9200

  chronograf:
    container_name: chronograf
    image: chronograf:1.7-alpine
    ports:
      - 8888:8888
    links:
      - influxdb
    environment:
      INFLUXDB_URL: http://influxdb:8086

  kibana:
    container_name: kibana
    image: kibana:6.5.4
    ports:
      - 5601:5601
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200